# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Repos/mwwhited/BlinkyTest/BlinkyTest.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2.xci
# IP: The module: 'design_1_auto_ds_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Repos/mwwhited/BlinkyTest/BlinkyTest.gen/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_ds_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Repos/mwwhited/BlinkyTest/BlinkyTest.gen/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_ds_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Repos/mwwhited/BlinkyTest/BlinkyTest.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2.xci
# IP: The module: 'design_1_auto_ds_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Repos/mwwhited/BlinkyTest/BlinkyTest.gen/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_ds_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Repos/mwwhited/BlinkyTest/BlinkyTest.gen/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_ds_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
