//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhitedUS.UI {
    
    
    public partial class DisplayAppointments : Microsoft.SPOT.Presentation.Window {
        
        internal Microsoft.SPOT.Presentation.Controls.Text Subject;
        
        internal Microsoft.SPOT.Presentation.Controls.Text StartTime;
        
        internal Microsoft.SPOT.Presentation.Controls.Text EndTime;
        
        internal Microsoft.SPOT.Presentation.Controls.Text Body;
        
        partial void OnComponentsInitialized();
        
        public DisplayAppointments() {
            this.InitializeComponents();
            this.OnComponentsInitialized();
        }
        
        private void InitializeComponents() {
            this.Width = 320;
            this.Height = 240;
            this.Background = new Microsoft.SPOT.Presentation.Media.SolidColorBrush(Microsoft.SPOT.Presentation.Media.ColorUtility.ColorFromRGB(0, 128, 0));
            // 
            // stackPanel3
            // 
            Microsoft.SPOT.Presentation.Controls.StackPanel stackPanel3 = new Microsoft.SPOT.Presentation.Controls.StackPanel();
            stackPanel3.Orientation = Microsoft.SPOT.Presentation.Controls.Orientation.Vertical;
            stackPanel3.VerticalAlignment = Microsoft.SPOT.Presentation.VerticalAlignment.Center;
            // 
            // Subject
            // 
            Subject = new Microsoft.SPOT.Presentation.Controls.Text();
            Subject.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            Subject.Font = Resources.GetFont(Resources.FontResources.small);
            Subject.TextContent = "Subject";
            stackPanel3.Children.Add(Subject);
            // 
            // StartTime
            // 
            StartTime = new Microsoft.SPOT.Presentation.Controls.Text();
            StartTime.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            StartTime.Font = Resources.GetFont(Resources.FontResources.small);
            StartTime.TextContent = "Start";
            stackPanel3.Children.Add(StartTime);
            // 
            // EndTime
            // 
            EndTime = new Microsoft.SPOT.Presentation.Controls.Text();
            EndTime.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            EndTime.Font = Resources.GetFont(Resources.FontResources.small);
            EndTime.TextContent = "End";
            stackPanel3.Children.Add(EndTime);
            // 
            // Body
            // 
            Body = new Microsoft.SPOT.Presentation.Controls.Text();
            Body.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            Body.Font = Resources.GetFont(Resources.FontResources.small);
            Body.TextContent = "Body";
            stackPanel3.Children.Add(Body);
            this.Child = stackPanel3;
        }
    }
}
