//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhitedUS.UI {
    
    
    public partial class DisplayClock : Microsoft.SPOT.Presentation.Window {
        
        partial void OnComponentsInitialized();
        
        public DisplayClock() {
            this.InitializeComponents();
            this.OnComponentsInitialized();
        }
        
        private void InitializeComponents() {
            this.Width = 320;
            this.Height = 240;
        }
    }
}
