//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhitedUS.UI {
    
    
    public partial class DisplayRadio : Microsoft.SPOT.Presentation.Window {
        
        internal Microsoft.SPOT.Presentation.Controls.Text station;
        
        internal Microsoft.SPOT.Presentation.Controls.Text volume;
        
        internal Microsoft.SPOT.Presentation.Controls.Text signal;
        
        internal Microsoft.SPOT.Presentation.Controls.Text channel;
        
        partial void OnComponentsInitialized();
        
        public DisplayRadio() {
            this.InitializeComponents();
            this.OnComponentsInitialized();
        }
        
        private void InitializeComponents() {
            this.Width = 320;
            this.Height = 240;
            this.Background = new Microsoft.SPOT.Presentation.Media.SolidColorBrush(Microsoft.SPOT.Presentation.Media.ColorUtility.ColorFromRGB(255, 255, 0));
            // 
            // stackPanel7
            // 
            Microsoft.SPOT.Presentation.Controls.StackPanel stackPanel7 = new Microsoft.SPOT.Presentation.Controls.StackPanel();
            stackPanel7.Orientation = Microsoft.SPOT.Presentation.Controls.Orientation.Vertical;
            stackPanel7.VerticalAlignment = Microsoft.SPOT.Presentation.VerticalAlignment.Center;
            // 
            // text7
            // 
            Microsoft.SPOT.Presentation.Controls.Text text7 = new Microsoft.SPOT.Presentation.Controls.Text();
            text7.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            text7.Font = Resources.GetFont(Resources.FontResources.small);
            text7.TextContent = "FM Radio (AR1010/I2C)";
            stackPanel7.Children.Add(text7);
            // 
            // station
            // 
            station = new Microsoft.SPOT.Presentation.Controls.Text();
            station.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            station.Font = Resources.GetFont(Resources.FontResources.small);
            station.TextContent = "station";
            stackPanel7.Children.Add(station);
            // 
            // volume
            // 
            volume = new Microsoft.SPOT.Presentation.Controls.Text();
            volume.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            volume.Font = Resources.GetFont(Resources.FontResources.small);
            volume.TextContent = "volume";
            stackPanel7.Children.Add(volume);
            // 
            // signal
            // 
            signal = new Microsoft.SPOT.Presentation.Controls.Text();
            signal.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            signal.Font = Resources.GetFont(Resources.FontResources.small);
            signal.TextContent = "signal";
            stackPanel7.Children.Add(signal);
            // 
            // channel
            // 
            channel = new Microsoft.SPOT.Presentation.Controls.Text();
            channel.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            channel.Font = Resources.GetFont(Resources.FontResources.small);
            channel.TextContent = "channel";
            stackPanel7.Children.Add(channel);
            this.Child = stackPanel7;
        }
    }
}
