//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhitedUS.UI {
    
    
    public partial class DisplayContact : Microsoft.SPOT.Presentation.Window {
        
        internal Microsoft.SPOT.Presentation.Controls.Text FullName;
        
        internal Microsoft.SPOT.Presentation.Controls.Text FileAs;
        
        internal Microsoft.SPOT.Presentation.Controls.Text HomeTelephoneNumber;
        
        internal Microsoft.SPOT.Presentation.Controls.Text MobileTelephoneNumber;
        
        internal Microsoft.SPOT.Presentation.Controls.Text BusinessTelephoneNumber;
        
        partial void OnComponentsInitialized();
        
        public DisplayContact() {
            this.InitializeComponents();
            this.OnComponentsInitialized();
        }
        
        private void InitializeComponents() {
            this.Width = 320;
            this.Height = 240;
            this.Background = new Microsoft.SPOT.Presentation.Media.SolidColorBrush(Microsoft.SPOT.Presentation.Media.ColorUtility.ColorFromRGB(0, 0, 255));
            this.Foreground = new Microsoft.SPOT.Presentation.Media.SolidColorBrush(Microsoft.SPOT.Presentation.Media.ColorUtility.ColorFromRGB(255, 255, 255));
            // 
            // stackPanel1
            // 
            Microsoft.SPOT.Presentation.Controls.StackPanel stackPanel1 = new Microsoft.SPOT.Presentation.Controls.StackPanel();
            stackPanel1.Orientation = Microsoft.SPOT.Presentation.Controls.Orientation.Vertical;
            stackPanel1.VerticalAlignment = Microsoft.SPOT.Presentation.VerticalAlignment.Center;
            // 
            // FullName
            // 
            FullName = new Microsoft.SPOT.Presentation.Controls.Text();
            FullName.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            FullName.Font = Resources.GetFont(Resources.FontResources.small);
            FullName.TextContent = "FullName";
            stackPanel1.Children.Add(FullName);
            // 
            // FileAs
            // 
            FileAs = new Microsoft.SPOT.Presentation.Controls.Text();
            FileAs.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            FileAs.Font = Resources.GetFont(Resources.FontResources.small);
            FileAs.TextContent = "FileAs";
            stackPanel1.Children.Add(FileAs);
            // 
            // HomeTelephoneNumber
            // 
            HomeTelephoneNumber = new Microsoft.SPOT.Presentation.Controls.Text();
            HomeTelephoneNumber.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            HomeTelephoneNumber.Font = Resources.GetFont(Resources.FontResources.small);
            HomeTelephoneNumber.TextContent = "HomeTelephoneNumber";
            stackPanel1.Children.Add(HomeTelephoneNumber);
            // 
            // MobileTelephoneNumber
            // 
            MobileTelephoneNumber = new Microsoft.SPOT.Presentation.Controls.Text();
            MobileTelephoneNumber.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            MobileTelephoneNumber.Font = Resources.GetFont(Resources.FontResources.small);
            MobileTelephoneNumber.TextContent = "MobileTelephoneNumber";
            stackPanel1.Children.Add(MobileTelephoneNumber);
            // 
            // BusinessTelephoneNumber
            // 
            BusinessTelephoneNumber = new Microsoft.SPOT.Presentation.Controls.Text();
            BusinessTelephoneNumber.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            BusinessTelephoneNumber.Font = Resources.GetFont(Resources.FontResources.small);
            BusinessTelephoneNumber.TextContent = "BusinessTelephoneNumber";
            stackPanel1.Children.Add(BusinessTelephoneNumber);
            this.Child = stackPanel1;
        }
    }
}
