//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhitedUS.UI {
    
    
    public partial class WeatherReport : Microsoft.SPOT.Presentation.Window {
        
        internal Microsoft.SPOT.Presentation.Controls.StackPanel reportPanel;
        
        internal Microsoft.SPOT.Presentation.Controls.Text title;
        
        internal Microsoft.SPOT.Presentation.Controls.Text location;
        
        internal Microsoft.SPOT.Presentation.Controls.Text temperature;
        
        internal Microsoft.SPOT.Presentation.Controls.Text wind;
        
        internal Microsoft.SPOT.Presentation.Controls.Text astronomy;
        
        internal Microsoft.SPOT.Presentation.Controls.Text condition;
        
        internal Microsoft.SPOT.Presentation.Controls.Image icon;
        
        internal Microsoft.SPOT.Presentation.Controls.ListBox forcast;
        
        partial void OnComponentsInitialized();
        
        public WeatherReport() {
            this.InitializeComponents();
            this.OnComponentsInitialized();
        }
        
        private void InitializeComponents() {
            this.Width = 320;
            this.Height = 240;
            this.Background = new Microsoft.SPOT.Presentation.Media.SolidColorBrush(Microsoft.SPOT.Presentation.Media.ColorUtility.ColorFromRGB(128, 128, 128));
            // 
            // reportPanel
            // 
            reportPanel = new Microsoft.SPOT.Presentation.Controls.StackPanel();
            reportPanel.Orientation = Microsoft.SPOT.Presentation.Controls.Orientation.Vertical;
            reportPanel.VerticalAlignment = Microsoft.SPOT.Presentation.VerticalAlignment.Center;
            reportPanel.Width = 320;
            // 
            // title
            // 
            title = new Microsoft.SPOT.Presentation.Controls.Text();
            title.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            title.Font = Resources.GetFont(Resources.FontResources.small);
            title.TextContent = "Yahoo weather";
            reportPanel.Children.Add(title);
            // 
            // location
            // 
            location = new Microsoft.SPOT.Presentation.Controls.Text();
            location.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            location.Font = Resources.GetFont(Resources.FontResources.small);
            location.TextContent = "City, State - Country";
            reportPanel.Children.Add(location);
            // 
            // temperature
            // 
            temperature = new Microsoft.SPOT.Presentation.Controls.Text();
            temperature.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            temperature.Font = Resources.GetFont(Resources.FontResources.small);
            temperature.TextContent = "63 F";
            reportPanel.Children.Add(temperature);
            // 
            // wind
            // 
            wind = new Microsoft.SPOT.Presentation.Controls.Text();
            wind.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            wind.Font = Resources.GetFont(Resources.FontResources.small);
            wind.TextContent = "5 mph";
            reportPanel.Children.Add(wind);
            // 
            // astronomy
            // 
            astronomy = new Microsoft.SPOT.Presentation.Controls.Text();
            astronomy.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            astronomy.Font = Resources.GetFont(Resources.FontResources.small);
            astronomy.TextContent = "sunrise sunset";
            reportPanel.Children.Add(astronomy);
            // 
            // condition
            // 
            condition = new Microsoft.SPOT.Presentation.Controls.Text();
            condition.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            condition.Font = Resources.GetFont(Resources.FontResources.small);
            condition.TextContent = "cloudy";
            reportPanel.Children.Add(condition);
            // 
            // icon
            // 
            icon = new Microsoft.SPOT.Presentation.Controls.Image();
            icon.HorizontalAlignment = Microsoft.SPOT.Presentation.HorizontalAlignment.Center;
            icon.Bitmap = Resources.GetBitmap(Resources.BitmapResources.Broken);
            reportPanel.Children.Add(icon);
            // 
            // forcast
            // 
            forcast = new Microsoft.SPOT.Presentation.Controls.ListBox();
            forcast.Width = 320;
            forcast.HorizontalAlignment = Microsoft.SPOT.Presentation.HorizontalAlignment.Center;
            // 
            // listBoxItem3
            // 
            Microsoft.SPOT.Presentation.Controls.ListBoxItem listBoxItem3 = new Microsoft.SPOT.Presentation.Controls.ListBoxItem();
            listBoxItem3.Width = 320;
            // 
            // text3
            // 
            Microsoft.SPOT.Presentation.Controls.Text text3 = new Microsoft.SPOT.Presentation.Controls.Text();
            text3.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            text3.Font = Resources.GetFont(Resources.FontResources.small);
            text3.TextContent = "forcast";
            listBoxItem3.Child = text3;
            forcast.Items.Add(listBoxItem3);
            // 
            // listBoxItem4
            // 
            Microsoft.SPOT.Presentation.Controls.ListBoxItem listBoxItem4 = new Microsoft.SPOT.Presentation.Controls.ListBoxItem();
            listBoxItem4.Width = 320;
            // 
            // text4
            // 
            Microsoft.SPOT.Presentation.Controls.Text text4 = new Microsoft.SPOT.Presentation.Controls.Text();
            text4.TextAlignment = Microsoft.SPOT.Presentation.Media.TextAlignment.Center;
            text4.Font = Resources.GetFont(Resources.FontResources.small);
            text4.TextContent = "forcast";
            listBoxItem4.Child = text4;
            forcast.Items.Add(listBoxItem4);
            reportPanel.Children.Add(forcast);
            this.Child = reportPanel;
        }
    }
}
